create or replace view v_prl_oisf_Done as
select i.entgid,
       i.ISFFlowType,
       i.ISFModelGid,
       i.ISFModelCode,
       i.ISFFlowGid,
       i.ISFNum,
       i.ISFLessee,
       i.ISFFillUsrName,
       i.ISFCreateDate,
       i.ISFStat,
       i.ISFStatText,
       i.ISFDepeCode,
       i.ISFCONTRACTDATE1,
       i.ISFCONTRACTDATE2,
       c.ISCFModelGid,
       c.ISCFModelCode,
       c.ISCFFlowGid,
       c.ISCFNum,
       c.ISCFFillUsrName,
       c.ISCFStat,
       c.ISCFFStat,
       t.ISTFModelGid,
       t.ISTFModelCode,
       t.ISTFFlowGid,
       t.ISTFNum,
       t.ISTFFillUsrName,
       t.ISTFStat,
       t.ISTFFStat
  from (select f.entgid,
               decode(f.FlowType, '10', 'ISF', '20', 'ISCF', 'MAll') ISFFlowType,
               f.modelgid ISFModelGid,
               wm.code ISFModelCode,
               f.flowgid ISFFlowGid,
               f.num ISFNum,
               f.lessee ISFlessee,
               f.fillusrname ISFFillUsrName,
               f.createdate ISFcreatedate,
               f.CONTRACTDATE1 ISFCONTRACTDATE1,
               f.CONTRACTDATE2 ISFCONTRACTDATE2,
               decode(f.stat,
                      '0',
                      '未开始',
                      '1',
                      '填写中',
                      '10',
                      '已提交，审批中',
                      '12',
                      '已同意',
                      '13',
                      '已否决',
                      '30',
                      '已完成',
                      '40',
                      '已终止合同',
                      '100',
                      '发起人结束流程',
                      f.Stat) ISFStatText,
               f.stat ISFStat,
               substr(f.FillDeptCode, 0, 4) ISFDepeCode
          from wf_prl_Oisf f, wf_flow wf, wf_model wm
         where f.entgid = wf.entgid
           and f.flowgid = wf.flowgid
           and f.Entgid = wm.EntGid
           and wf.ModelGid = wm.ModelGid
           and wf.stat = 3
           and f.stat in ('30', '40', '已完成')
           and f.flowtype in (10, 20)
        union
        select f.entgid,
               decode(f.FlowType, '10', 'ISF', '20', 'ISCF', 'MAll') ISFFlowType,
               f.modelgid ISFModelGid,
               wm.code ISFModelCode,
               f.flowgid ISFFlowGid,
               f.num ISFNum,
               f.lessee ISFlessee,
               f.fillusrname ISFFillUsrName,
               f.createdate ISFcreatedate,
               f.CONTRACTDATE1 ISFCONTRACTDATE1,
               f.CONTRACTDATE2 ISFCONTRACTDATE2,
               decode(f.stat,
                      '0',
                      '未开始',
                      '1',
                      '填写中',
                      '10',
                      '已提交，审批中',
                      '12',
                      '已同意',
                      '13',
                      '已否决',
                      '30',
                      '已完成',
                      '40',
                      '已终止合同',
                      '100',
                      '发起人结束流程',
                      f.Stat) ISFStatText,
               f.stat ISFStat,
               substr(f.FillDeptCode, 0, 4) ISFDepeCode
          from wf_prl_Oisf f, wf_model wm
         where f.Entgid = wm.EntGid
           and f.ModelGid = wm.ModelGid
           and f.flowtype = 30
           and f.stat in ('30', '40')) i,
       (select f.entgid,
               f.modelgid ISCFModelGid,
               wm.code ISCFModelCode,
               f.flowgid ISCFFlowGid,
               f.num ISCFNum,
               f.fillusrname ISCFfillUsrName,
               decode(f.stat,
                      '0',
                      '未开始',
                      '1',
                      '填写中',
                      '10',
                      '已提交，审批中',
                      '12',
                      '已同意',
                      '13',
                      '已否决',
                      '30',
                      '已完成',
                      '40',
                      '已终止合同',
                      '100',
                      '发起人结束流程',
                      f.Stat) ISCFStat,
               decode(wf.stat,
                      '0',
                      '未执行',
                      '1',
                      '待执行',
                      '2',
                      '执行中',
                      '3',
                      '已完成',
                      '4',
                      '已停止',
                      '5',
                      '已作废',
                      '6',
                      '已超时') ISCFFStat,
               f.oldflowgid
          from wf_prl_Oisf f, wf_flow wf, wf_model wm
         where f.entgid = wf.entgid
           and f.flowgid = wf.flowgid
           and f.Entgid = wm.EntGid
           and wf.ModelGid = wm.ModelGid
           and wf.stat < 4
           and f.stat in ('30', '40', '已完成')) c,
       (select f.entgid,
               f.modelgid ISTFModelGid,
               wm.code ISTFModelCode,
               f.flowgid ISTFFlowGid,
               f.num ISTFNum,
               f.fillusrname ISTFfillUsrName,
               decode(f.stat,
                      '0',
                      '未开始',
                      '1',
                      '填写中',
                      '10',
                      '已提交，审批中',
                      '12',
                      '已同意',
                      '13',
                      '已否决',
                      '30',
                      '已完成',
                      '40',
                      '已终止合同',
                      '100',
                      '发起人结束流程',
                      f.Stat) ISTFStat,
               decode(wf.stat,
                      '0',
                      '未执行',
                      '1',
                      '待执行',
                      '2',
                      '执行中',
                      '3',
                      '已完成',
                      '4',
                      '已停止',
                      '5',
                      '已作废',
                      '6',
                      '已超时') ISTFFStat,
               f.oldflowgid
          from wf_prl_Oistf f, wf_flow wf, wf_model wm
         where f.entgid = wf.entgid
           and f.flowgid = wf.flowgid
           and f.Entgid = wm.EntGid
           and wf.ModelGid = wm.ModelGid
           and wf.stat < 4
           and f.stat in ('已完成')) t
 where i.entgid = c.entgid(+)
   and i.ISFFlowGid = c.oldflowgid(+)
   and i.entgid = t.entgid(+)
   and i.ISFFlowGid = t.oldflowgid(+)
 order by i.ISFcreatedate desc;
